export const PROCESS_STATUS = {
    PDTE_ENTREVISTA : 'PDTE. ENTREVISTA',
    ENTREVISTADO : 'ENTREVISTADO',
    ESPERANDO_CV : 'ESPERANDO CV',
    RECHAZADO: 'RECHAZADO',
    CONTRATADO : 'CONTRATADO'
} 